### ISSUE TITLE
installation error on Windows 10

### ISSUE THREAD

**Issue by arfogg** [pik-copan/pyunicorn#160]
Hi,
Thanks for providing this very useful python package. I am having trouble installing it. 
My system is Windows 10 x64

Following the install instructions on your github homepage leads me to this error:

```
pyunicorn-master>pip install .
...
Building wheels for collected packages: pyunicorn
  Building wheel for pyunicorn (pyproject.toml) ... error
  error: subprocess-exited-with-error
 ...
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.28.29910\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyunicorn
Failed to build pyunicorn
ERROR: Could not build wheels for pyunicorn, which is required to install pyproject.toml-based projects
```

I have also tried to follow through the steps outlined in another issue: #127 
which gives me this error:

```
pyunicorn_whl>pip install pyunicorn-0.6.1-cp37-cp37m-win_amd64.whl
ERROR: pyunicorn-0.6.1-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform.
```

please could you help me to solve this, so I can install pyunicorn.

sorry for the open and close below - I didn't realise some keyboard shortcuts!

Alexandra Fogg

**Comment by ntfrgl** [comment]
Hi @arfogg,

It seems like the second approach won't work for you, because that wheel was built for a different CPU architecture.

Regarding the first (correct) approach, the output you've provided doesn't contain enough information for me to identify the source of your problem. Please make sure to install the latest version of Microsoft C++ Build Tools, as suggested in a [related issue](https://github.com/pik-copan/pyunicorn/issues/159#issuecomment-1099543050). In case the problem remains, please run `pip install -vvv .` to get more detailed output, and post the full error message here - except, of course, any sensitive information there might be.

**Comment by arfogg** [comment]
Hi @ntfrgl ,

Thanks for getting back to me so quickly! 

I have updated my version of C++ build tools, it now reads in the developer command prompt as:
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools>cl
Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30143 for x86
Copyright (C) Microsoft Corporation.  All rights reserved. 
```


In conda I ran `pip install -vvv .`, and attach the full output and error here.
[pyunicorn_install_error.txt](https://github.com/pik-copan/pyunicorn/files/8520554/pyunicorn_install_error.txt)

my version of pip is: 22.0.4

i'm grateful for any suggestions on what to try next!

Alexandra

**Comment by ntfrgl** [comment]
Thanks for your installation report!

We're now facing some minor issues with Microsoft VS, which were previously avoided by relying on GCC for compiling the Cython/C extensions. With the commit above, I've hopefully resolved the errors showing up in your report, although there might be some more lurking behind. Since I don't have access to a Windows machine, may I kindly ask you to try installing again from the newest commit? It might take us a few more iterations until we surface all the Windows-specific issues, but I would like to resolve them.

**Comment by arfogg** [comment]
Thanks for looking into this, I'm very happy to be a tester for any Windows-specific issues!

I'm not 100% sure I have installed via the new commit, but this is the process I did:

Found the new commit (by clicking on the commit and then "Browse files"): 
https://github.com/pik-copan/pyunicorn/tree/79ded90816f49274ab6ac91febe50e4dad7b710a

Clicked "Code" and "Download ZIP"

And then, once the zipped files are extracted, I installed as before, using `pip install -vvv .`

Error and output are similar to before (see text file 
[pyunicorn_install_error_after_commit.txt](https://github.com/pik-copan/pyunicorn/files/8542551/pyunicorn_install_error_after_commit.txt) ) - maybe I haven't installed your updates correctly? Please could you let me know how to ensure I have installed the version including your current updates.

Alexandra

**Comment by ntfrgl** [comment]
_Update:_ Yes, your process was correct, thank you! The other way would be to `git clone` the repository once onto your computer, and then simply to `git pull` whenever you'd like to receive updates. Your report shows that we have indeed made progress. The new errors are of the sort I expected, and I hope to get around to addressing them by this weekend.

_Brief explanation:_ As you can see by comparing the outputs before and after my previous commit, the compiler invocation warnings in lines 94-95 (old) are gone, and instead of getting stuck with errors from `climate/_ext/src_numerics.c` in lines 99-110 (old), the compiler now fails at the next source file, `core/_ext/src_numerics.c` in lines 149-150 (new).

**Comment by arfogg** [comment]
Thanks for getting back to me!
I will keep an eye out for your next update, and be sure to test it out.

Alexandra

**Comment by mixue-t** [comment]
Hi, I am facing the same issues as above. Is there a solution for this now? Super keen on using this toolbox!

**Comment by ntfrgl** [comment]
I am reopening this issue, as it seems to have been closed without confirming a resolution.

@arfogg, please accept our apologies for a lasting lack of resources in addressing this issue. I hope that you have found a workaround for your needs, but would be delighted if you gave this package another chance.

The commits above address all the issues which were visible so far in the installation logs on Windows. @fkuehlein, @zugnachpankow, @mixue-t, may I kindly ask you to attempt a fresh installation on Windows by following the updated instructions in the [`README`](https://github.com/pik-copan/pyunicorn/blob/master/README.rst#installation)?

**Comment by linh-hk** [comment]
Hi, 

I also had error while installing. Which is

[numerics.obj : error LNK2001: unresolved external symbol drand48](https://www.google.com/search?q=numerics.obj+:+error+LNK2001:+unresolved+external+symbol+drand48)

and tried with all the previous methods, including the installation of Microsoft C++ Build Tools in issue #159. It did not work.

It seems that drand48 and erand48 are not included in the VC if I downloaded as the video said. 
Eventually, I just installed Visual Studio code and install the C/C++ Extensions from there and the problem was magically solved.

I just record this here if anyone has the same issue.
Thanks.

**Comment by ntfrgl** [comment]
Hi @linh-hk, thank you for reporting your situation.

We're currently in the process of removing the last barriers to the installation on Windows using MSVC. Because `drand48()` is not defined in MSVC, my latest commits above (16 hours ago) circumvented this call, and several other known problems. Therefore it seems more likely that your issues were actually resolved either by using the most recent code, or by using a different compiler than MSVC.

Do I understand correctly that the Windows installation is now fully functional for you? May I kindly ask you to retry a fresh installation and to provide the entire output of `pip install -vvv .`, as was done in a [comment above](https://github.com/pik-copan/pyunicorn/issues/160#issuecomment-1103798894)? This would be very helpful in assessing the situation.

**Comment by linh-hk** [comment]
Hi @ntfrgl , sorry for the late reply ... I didn't check the notification...

I successfully install the package on a Window instance on was ec2. I think the issue is solved. When I import the library, it gets me:
pyunicorn: Package netCDF4 could not be loaded. Some functionality in class Data might not be available!
pyunicorn: Package netCDF4 could not be loaded. Some functionality in class NetCDFDictionary might not be available!
(also reported [here](https://github.com/pik-copan/pyunicorn/issues/127#issuecomment-692749125) )

I believe this error is not exclusive to installation on Windows because when I import pyunicorn in Ubuntu it reported the same. I did not have to use any functions that depends on netCDF4 but tried to make it go away by separately install netcdf4 using conda. Please fix it anyway.

Thanks.

**Comment by ntfrgl** [comment]
Thank you once more, @linh-hk! I am glad to hear that the installation is working for you.

I have addressed those import warnings in the commit above.

**Comment by ntfrgl** [comment]
We had several more reports of successful installations on Windows, hence this issue can be closed.
