### ISSUE TITLE
QST: Add scripts using pyunicorn for detecting regime shifts in sets of time series as pyunicorn example or as separate github repo? 

### ISSUE THREAD

**Issue by jdonges** [pik-copan/pyunicorn#84]
This is referring specifically to the scripts used for generating the results reported in:

J.F. Donges, R.V. Donner, N. Marwan, S.F.M. Breitenbach, K. Rehfeld, and J. Kurths,
Nonlinear regime shifts in Holocene Asian monsoon variability: Potential impacts on cultural change and migratory patterns,
Climate of the Past 11, 709-741 (2015),
DOI: 10.5194/cp-11-709-2015.

These scripts are highly generalizable to use with other datasets and with other measures (e..g, additional recurrence analysis quantifiers) or methods (e.g., visibility graphs instead of recurrence networks).

**Comment by wbarfuss** [comment]
This is a strategic decision, of course - with no right or wrong answer.
If these scripts have no major dependence on the pyunicorn code base, I would always prefer multiple, small packages or scripts - mainly because I think, these are more user friendly (saves trouble with installing and dependency issues for code, I might not care about at all)

**Comment by jdonges** [comment]
I decided to open a new repository for these scripts, need to create a reference to them in the examples section of the pyunicorn documentation: https://github.com/pik-copan/pyregimeshifts
